language: nix
sudo: required
compiler:
- gcc
- clang
os:
- linux
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
cache: yarn
install:
- ./scripts/install.sh
- nvm install 8
- nvm use 8
- npm install
before_script:
- parity --chain test/parity-genesis.config --jsonrpc-apis all &
- sleep 20
- npm run before-tests
- sleep 20
- killall parity
script:
- npm run compile
- npm run localnode:parity &
- npm run deploy:development
- npm run test
- npm run oyente
after_script:
- cat testrpc.log
