language: nix
sudo: required
compiler:
- gcc
- clang
os:
- linux
env:
- CXX=g++-4.8 TRAVIS_NODE_VERSION=8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
cache: yarn
install:
- ./scripts/install.sh
- npm install
before_script:
- npm run localnode:background
script:
- npm run compile
- npm run deploy:development
- npm run test
after_script:
- npm run coveralls
- cat testrpc.log
