language: node_js
node_js:
- '8'
compiler:
- gcc
- clang
os:
- linux
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
cache: yarn
before_script:
- testrpc -l 6979000 > testrpc.log &
after_script:
- npm run coveralls
- cat testrpc.log
