language: nix
sudo: required
compiler:
- gcc
- clang
os:
- linux
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
cache: yarn
install:
- nvm install 8
- nvm use 8
- npm install
script:
- npm run compile &> compile.log || cat compile.log
- npm run devchain:parity > parity.log &
- sleep 20
- npm run deploy:development
- ./tempscript.sh
- npm run test
- npm run oyente
after_script:
- cat parity.log
